program: train.py

method: bayes

metric:
  name: test_accuracy
  goal: maximize

parameters:
  learning_rate:
    min: 1.e-4
    max: 1.e-3

  alpha:
    min: 0.
    max: 0.99

  n_epochs:
    value: 15

  keep_weights:
    value: False
  