# Wandb default config. file

n_epochs:
  value: 999

learning_rate:
  value: 1.e-4

batch_size:
  value: 64

model:
  # "Conv1D", "Conv2D", "MLP", "Trans"
  value: "MLP"

subsample:
  value: 4

dropout:
  value: 0.5

weights_init:
  value: True

alpha:
  value: 2.

# TRANS PARAMS
word_length:
  value: 16

n_head:
  value: 2

n_layers:
  value: 2
