# Wandb default config. file

n_epochs:
  value: 999

keep_weights:
  value: True

learning_rate:
  value: 1.e-4

batch_size:
  value: 64

model:
  # "Conv1D", "Conv2D", "MLP", "Trans", "Noise"
  value: "MLP"

subsample:
  value: 16

dropout:
  value: 0.8

weights_init:
  value: False

alpha:
  value: 1.

signal_length:
  value: 8192

target_length:
  value: 128

denoiser:
  value: True

# TRANS PARAMS
word_length:
  value: 16

n_head:
  value: 2

n_layers:
  value: 2
