# Wandb default config. file

n_epochs:
  value: 999

learning_rate:
  value: 0.0001

batch_size:
  value: 8

model:
  # "Conv1D", "Conv2D", "MLP"
  value: "MLP"

subsample:
  value: 4

dropout:
  value: 0.5

weights_init:
  value: False
